boutique_galerie_homepage:
    path:     /categorie
    defaults: { _controller: BoutiqueGalerieBundle:Galerie:index }

boutique_galerie_panier:
    path:     /panier
    defaults: { _controller: BoutiqueGalerieBundle:Galerie:panier }

boutique_galerie_recette:
    path:     /panierrecette/{idRecette}
    defaults: { _controller: BoutiqueGalerieBundle:Galerie:panierRecette }

boutique_galerie_ajoutpanier:
    path:     /ajoutpanier
    defaults: { _controller: BoutiqueGalerieBundle:Galerie:ajoutPanier }

boutique_galerie_suppanier:
    path:     /suppanier/{id}
    defaults: { _controller: BoutiqueGalerieBundle:Galerie:supPanier }

boutique_galerie_actupanier:
    path:     /actupanier
    defaults: { _controller: BoutiqueGalerieBundle:Galerie:actuPanier }

boutique_galerie_validepanier:
    path:     /validepanier
    defaults: { _controller: BoutiqueGalerieBundle:Galerie:marche }

boutique_galerie_validemarche:
    path:     /validemarche
    defaults: { _controller: BoutiqueGalerieBundle:Galerie:validemarche }
