accueil_accueil_homepage:
    path:     /
    defaults: { _controller: AccueilAccueilBundle:Accueil:index }

formConnexion:
    path:     /connexion
    defaults: { _controller: AccueilAccueilBundle:Accueil:formulaireConnexion }

inscriptionClient:
    path:     /inscription
    defaults: { _controller: AccueilAccueilBundle:Accueil:inscription }

accueil_accueil_contact:
    path:     /contact
    defaults: { _controller: AccueilAccueilBundle:Accueil:contact }

passwordForget:
    path:     /retrouverMotdePasse
    defaults: { _controller: AccueilAccueilBundle:Accueil:contact }

goadministrator_administration:
    path:     /pagePrincipaleAdmin
    defaults: { _controller: AdministratorAdministrationAdminBundle:Default:pageAdminAccueil }