administrator_administration_admin_homepage:
    path:     /hello/{name}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Default:index }

administrator_administration_admin_suiv_comm:
    path:     /suivitCommandes
    defaults: { _controller: AdministratorAdministrationAdminBundle:Gerer:suivitDesCommandes }

administrator_administration_admin_gererProduits:
    path:     /gererProduits
    defaults: { _controller: AdministratorAdministrationAdminBundle:Produits:index }

administrator_administration_admin_gererTheCategories:
    path:     /gererCategoriesl
    defaults: { _controller: AdministratorAdministrationAdminBundle:Gerer:lesCategories }

administrator_administration_admin_gerer_News:
    path:     /gererNews
    defaults: { _controller: AdministratorAdministrationAdminBundle:Gerer:lesNews }

administrator_administration_admin_gerer_Recettes:
    path:     /gererRecettes
    defaults: { _controller: AdministratorAdministrationAdminBundle:Recette:base}

administrator_administration_admin_gerer_Clients:
    path:     /gererClients
    defaults: { _controller: AdministratorAdministrationAdminBundle:Gerer:lesCoordsClients }

administrator_administration_admin_add_Utilisateur_admin:
    path:     /gererUtil
    defaults: { _controller: AdministratorAdministrationAdminBundle:Gerer:lesUtilisateursAdmins }

administrator_administration_admin_gerer_Utilisateur_admin:
    path:     /gererUtilisateurs
    defaults: { _controller: AdministratorAdministrationAdminBundle:Gerer:administrationDesUtilisateursAdmins }

administrator_ajout_recette:
    path:     /ajoutrecette
    defaults: { _controller: AdministratorAdministrationAdminBundle:Recette:ajout }

administration_admin_ajoutIngredient:
    path:     /ajoutingredient/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Recette:ajoutingredient }

administration_admin_supprimerIngredient:
    path:     /supprimeringredient/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Recette:supprimerIngredient }

administration_admin_supprimerRecette:
    path:     /supprimerrecette/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Recette:supprimer }

administration_admin_modifierRecette:
    path:     /modifierrecette/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Recette:modifier }

administration_admin_modifierbisRecette:
    path:     /modifierbisrecette/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Recette:modifierbis }

administrator_administration_admin_gerer_notre_histoire:
    path:     /gererHist
    defaults: { _controller: AdministratorAdministrationAdminBundle:Histoire:pageAccueilGestionHistoire }

administrator_ajout_categorie:
    path:     /ajoutcategorie
    defaults: { _controller: AdministratorAdministrationAdminBundle:Produits:ajoutCat }

administrator_supprimer_categorie:
    path:     /supprimercategorie/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Produits:supprimerCategorie }

administrator_modifier_categorie:
    path:     /modifiercategorie/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Produits:modifierCategorie }

administration_admin_modifierbiscategorie:
    path:     /modifierbiscategorie/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Produits:modifierbisCategorie}

administrator_ajout_article:
    path:     /ajoutarticle/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Produits:ajoutArt}

administrator_modifier_article:
    path:     /modifierarticle/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Produits:modifierArt}

administration_admin_modifierbisarticle:
    path:     /modifierbisarticle/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Produits:modifierbisArt}

administrator_supprimer_article:
    path:     /supprimerarticle/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Produits:supprimerArt}

administrator_base_article:
    path:     /basearticle/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Produits:baseArt}

administration_admin_demdeActionsClient:
    path:     /quoiFaireClient/
    defaults: { _controller: AdministratorAdministrationAdminBundle:Gerer:choixActionsClients }

administration_admin_PREresultatChercherClient:
    path:     /preRecherche/
    defaults: { _controller: AdministratorAdministrationAdminBundle:Gerer:preResultatchercheClients }

administration_admin_resultatChercherClient:
    path:     /resultatRecherche/
    defaults: { _controller: AdministratorAdministrationAdminBundle:Gerer:resultatchercheClients }

administrator_administration_admin_actions_Utilisateur_admin:
    path:      /resultatsClients
    defaults: { _controller: AdministratorAdministrationAdminBundle:Gerer:gestionUtilisateurs }

administrator_administration_admin_modifierUser:
    path:      /modifierUtilisateur{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Gerer:modifierUser }

administrator_mail_redaction:
    path:      /redactionmail
    defaults: { _controller: AdministratorAdministrationAdminBundle:Newsletter:redaction }

administrator_mail_validation:
    path:      /validationmail
    defaults: { _controller: AdministratorAdministrationAdminBundle:Newsletter:validation }

administrator_mail_previsualisation:
    path:      /previsualisation
    defaults: { _controller: AdministratorAdministrationAdminBundle:Newsletter:previsualisation }

administrator_marches_index:
    path:      /marchesadmin
    defaults: { _controller: AdministratorAdministrationAdminBundle:Marches:index }

administrator_marches_ajout:
    path:      /marchesajout
    defaults: { _controller: AdministratorAdministrationAdminBundle:Marches:ajout }

administrator_marches_supp:
    path:      /marchessupp/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Marches:supp }

administrator_marches_modif:
    path:      /marchemodif/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Marches:modif }

administrator_marches_modifbis:
    path:      /marchemodifbis/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Marches:modifbis }

administrator_administration_admin_gerer_notre_histoire:
    path:     /gererHist
    defaults: { _controller: AdministratorAdministrationAdminBundle:Histoire:pageAccueilGestionHistoire }

administrator_administration_admin_quoiFaireHistoire:
    path:      /ModifSupprHistoire
    defaults: { _controller: AdministratorAdministrationAdminBundle:Histoire:modificationActionHistoire }

administrator_administration_admin_ajouterHistoire:
    path:      /ajoutHistoire
    defaults: { _controller: AdministratorAdministrationAdminBundle:Histoire:ajouterHistoire }

administrator_administration_admin_modifierHistoire:
    path:      /modifHistoire/{articleId}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Histoire:modifierHistoire }

administrator_administration_admin_ajouterBisBHistoire:
    path:      /ajoutBisHistoire
    defaults: { _controller: AdministratorAdministrationAdminBundle:Histoire:ajouterHistoireBis }

administrator_news_index:
    path:      /newsadmin
    defaults: { _controller: AdministratorAdministrationAdminBundle:News:index }

administrator_news_ajout:
    path:      /newsajout
    defaults: { _controller: AdministratorAdministrationAdminBundle:News:ajout }

administrator_news_supp:
    path:      /newssupp/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:News:supp }

administrator_news_modif:
    path:      /newsmodif/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:News:modif }

administrator_news_modifbis:
    path:      /newsmodifbis/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:News:modifbis }

administrator_commande_cherche:
    path:      /commandecherche
    defaults: { _controller: AdministratorAdministrationAdminBundle:Commande:index }

administrator_commande_resultat:
    path:      /commanderesultat
    defaults: { _controller: AdministratorAdministrationAdminBundle:Commande:resultat }

administrator_commande_option:
    path:      /commandeoption
    defaults: { _controller: AdministratorAdministrationAdminBundle:Commande:option }

administrator_commande_supprimer:
    path:      /commandesupprimer/{id}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Commande:supprimer }

administrator_commande_imprimer:
    path:      /commandeimprimer/{commandes}
    defaults: { _controller: AdministratorAdministrationAdminBundle:Commande:imprimer }
